services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
